language: C
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - cabal-install-2.0
      - ghc-8.2.2
    sources:
      - hvr-ghc

cache:
  directories:
    - $HOME/.cabal/
    - $HOME/.ghc/

install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/8.2.2/bin:/opt/cabal/2.0/bin:$PATH
  - cd $HOME/agda-presburger/travis/
  - travis_wait 50 ./install_agda.sh
  - cd $HOME/agda-presburger/

script:
  - agda --safe src/Presburger.agda

